name: Add bookmark
run-name: Add bookmark (${{ inputs.url }})

on:
  workflow_dispatch:
    inputs:
      url:
        description: The URL to bookmark.
        required: true
        type: string
      quote:
        description: Add a quote from the bookmark. Optional.
        type: string
      notes:
        description: Notes about the bookmark.
        type: string
      date:
        description: Date (YYYY-MM-DD). The default date is today.
        type: string
      tags:
        description: Add tags to categorize the book. Separate each tag with a comma. Optional.
        type: string

permissions:
  contents: write

jobs:
  add-bookmark:
    runs-on: ubuntu-latest
    name: Add bookmark
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bookmark action
        uses: library-pals/bookmark-action@v7.0.2
        with:
          fileName: _data/bookmarks.json
          additional-properties: quote,notes,tags,date
          export-image: false
      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m  "Bookmark ${{ env.BookmarkTitle }}"
          git push
